// src/components/Hero.tsx
import * as React from "react";
import LayoutStyles from "@styles/layouts/layout.module.scss";
import HeroStyles from "@styles/components/Hero.module.scss";

export default function Hero() {
  const [weather, setWeather] = React.useState("");

  // get data from Worker

  return (
    <section className={HeroStyles.hero}>
      <div className={LayoutStyles.container}>
        <h1 className={HeroStyles.title}>
          <p>Hey 👋</p>
          <p>
            I'm Joseph Shambrook, a front-end Developer living in
            {weather ? ` ${weather}` : ""} Edinburgh, UK, focused on creating
            great websites and coaching others.
          </p>
          <p></p>
        </h1>
      </div>
    </section>
  );
}

// src/components/Hero.svelte
<section class="hero">
  <div class="container">
    <h1 class="title">
      <p>
        Hey <span class="wave">👋</span>
      </p>
      <p>
        I'm Joseph Shambrook, a front&#8209;end developer living in
        Edinburgh, UK, focused on creating
        great websites and coaching others.
      </p>
      <p></p>
    </h1>
  </div>
</section>


<style lang="postcss">
  @layer components {
    .hero {
      padding-block-end: 2rem;

      @media (--js-bp-lg) {
        padding-block-end: 5rem;
      }

      p {
        margin-block: 0;
      }
    }

    .title {
      color: var(--js-color-white);
      font-size: var(--js-heading-hero);
      font-weight: 700;
      line-height: 1.4;
      text-transform: none;
    }

    .wave {
      display: inline-block;
      transform-origin: bottom right;

      @media (prefers-reduced-motion: no-preference) {
        animation: wave 750ms ease-in-out;
        animation-iteration-count: 2;
        animation-delay: 1s;
      }
    }

  }

  @keyframes wave {
    50% {
      transform: rotate(30deg);
    }
  }
</style>;
